### ISSUE TITLE
Opção para persistir a mascara.

### ISSUE THREAD

**Issue by alexsandro-xpt** [assisrafael/angular-input-masks#107]
Atualmente um mascara de CPF 000.000.000-00 equivale a  00000000000.
Sugiro que seja útil uma opção para persistir o valor mascarado, não apenas no input como é hoje para que possamos grava-lo no banco de dados.
##

**Comment by assisrafael** [comment]
Please submit a PR for implementing such behaviour if you wish.

**Comment by kristiantenfen** [comment]
Alguma novidade sobre esta funcionalidade?

**Comment by ianldgs** [comment]
Também estou precisando, o jeito foi reformatar os valores antes de mandar pra integração com o outro sistema. Quando eu tiver um tempo desenvolvo isso

**Comment by assisrafael** [comment]
Duplicate of #172
