### ISSUE TITLE
Unable to install latest commit. Maybe create a new minor release?

### ISSUE THREAD

**Issue by aktary** [assisrafael/angular-input-masks#109]
Git is throwing an error when I try to install the latest commit:

>david@david-VirtualBox:~/projects/scale (revised-calcs)$ bower install angular-input-masks#3cb5349bcce0cbcbf85bf4e3262648a329052fc6 --save
>bower not-cached    git://github.com/assisrafael/bower-angular-input-masks.git#3cb5349bcce0cbcbf85bf4e3262648a329052fc6
>bower resolve       git://github.com/assisrafael/bower-angular-input-masks.git#3cb5349bcce0cbcbf85bf4e3262648a329052fc6
>bower checkout      angular-input-masks#3cb5349bcce0cbcbf85bf4e3262648a329052fc6
>bower not-cached    git://github.com/assisrafael/bower-angular-input-masks.git#3cb5349bcce0cbcbf85bf4e3262648a329052fc6
>bower resolve       git://github.com/assisrafael/bower-angular-input-masks.git#3cb5349bcce0cbcbf85bf4e3262648a329052fc6
>bower checkout      angular-input-masks#3cb5349bcce0cbcbf85bf4e3262648a329052fc6
>bower ECMDERR       Failed to execute "git checkout 3cb5349bcce0cbcbf85bf4e3262648a329052fc6", exit code of #128 fatal: reference is not a tree: 3cb5349bcce0cbcbf85bf4e3262648a329052fc6

>Additional error details:
>fatal: reference is not a tree: 3cb5349bcce0cbcbf85bf4e3262648a329052fc6

...any idea why?  Would this be resolved by tagging the commit as a minor release?

**Comment by assisrafael** [comment]
This commit does not exist in the bower-angular-input-masks repository. If you want to use the master you need to install from npm.
