### ISSUE TITLE
Undefined in input using  ui-number-mask="0"

### ISSUE THREAD

**Issue by Codestudios** [assisrafael/angular-input-masks#111]
I am setting ui-number-mask="0" and when I change the value of model directly to 0  like this

$scope.product.quantity = 0;

the input show me undefined, 

This only happen with this ui-number-mask="0", because when I put 2 ui-number-mask="2" its work perfectly.

**Comment by rgiosa** [comment]
+1

**Comment by sdrioux** [comment]
+1

**Comment by rafaelmohedano** [comment]
the same error for me

**Comment by omnibrain** [comment]
+1

Same for ui-percentage-mask

**Comment by keithmullins** [comment]
+1

**Comment by jkchavarrom2015** [comment]
+1

**Comment by keithmullins** [comment]
I got this working in my own project by adding this line to the `parser()` method of the `NumberMaskDirective`: `if(value === undefined) value = '0';`

    function parser(value) {
        if(value === undefined) value = '0';

        if(ctrl.$isEmpty(value)) {
            return value;
        }
        // etc.
    }

I don't know the library well enough just yet to know if this is the correct thing to do, but it's certainly working for me.

**Comment by neocite** [comment]
+1
I "resolved" to put "ui-money-mask=2"

**Comment by ardentum** [comment]
Hi guys. I used this temp workaround with directive decoration. Maybe it will help you too.

```javascript
angular.module('ui.utils.masks').config(function ($provide) {
  $provide.decorator('uiNumberMaskDirective', function($delegate) {
    var directive = $delegate[0];
    var link = directive.link;

    directive.compile = function() {
      return function(scope, element, attrs, ngModelCtrl) {
        link.apply(this, arguments);

        ngModelCtrl.$formatters.unshift(function (value) {
          if (value === 'undefined') { value = ''; }
          return value;
        });
      };
    };

    return $delegate;
  });
});
```

**Comment by rcschettino** [comment]
+1
The same error for me.

**Comment by diegogodinho** [comment]
+1

**Comment by skarface** [comment]
+1

**Comment by avew** [comment]
+1
