### ISSUE TITLE
Não está identificando a configuração de "dinheiro" correta do navegador

### ISSUE THREAD

**Issue by schinaider** [assisrafael/angular-input-masks#116]
![1](https://cloud.githubusercontent.com/assets/6196225/9439192/377c830c-4a3b-11e5-9e0e-ff432da39fb1.png)

Olá, o meu navegador está configurado todo em PT-BR, o sistema operacional também. Já testei em outros navegadores, e acontece a mesma coisa. Não sei, talvez eu tenha entendido errado, porém você disse que basta, apenas, ter as configurações de idioma corretas no navegador para ser refletido nas diretivas, correto?

Porém a mask money aparece como se eu estivesse nos EUA. Segue:

![2](https://cloud.githubusercontent.com/assets/6196225/9439265/ac8c35ac-4a3b-11e5-9cca-18142899ce04.png)

**Comment by assisrafael** [comment]
Have you included the proper angular locale file?

**Comment by schinaider** [comment]
Sorry, but i don't know what file is this... There is a tutorial, in documentation, about this?

**Comment by marioguadanhim** [comment]
I had the same problem.

**Comment by assisrafael** [comment]
Take a look at: https://docs.angularjs.org/guide/i18n

**Comment by marioguadanhim** [comment]
It Works! Thanks Rafael

**Comment by assisrafael** [comment]
Now it is in the README too: https://github.com/assisrafael/angular-input-masks#internationalization

**Comment by schinaider** [comment]
Thanks
