### ISSUE TITLE
bug de digitação

### ISSUE THREAD

**Issue by raivieira** [assisrafael/angular-input-masks#124]
Olá, em alguns campos como Phone number, CPF, CNPJ, CEP e Data, quando se apaga um número no meio do campo, o cursor pula para o final.

Ex CEP: 89027-710, se for apagado o número 8 (primeiro número), o cursor vai pular para o final do campo, depois do número 710.

**Comment by assisrafael** [comment]
Unfortunately, the current implementation does not keep track of the cursor position.

**Comment by assisrafael** [comment]
Duplicated of #122
