### ISSUE TITLE
ui number and ui negative do not work together

### ISSUE THREAD

**Issue by Sevensnake** [assisrafael/angular-input-masks#135]
my problem I need 
ui-number-mask="4" ui-negative-number ui-percentage-mask
all to work together. If I have percentage I cannot have mask. I can type it but when loading the data only one works and not the other.
##

**Comment by assisrafael** [comment]
I'm not sure about what is your use case. Can you describe it in more details?

**Comment by Sevensnake** [comment]
I almost forgot about this.  I have percentage sign and Ui-number-mask that equal 4. if you have all three directives at the same time like I said above one cancels the other out.

**Comment by assisrafael** [comment]
Those two directives (`ui-percentage-mask` and `ui-number-mask`) were not designed to be used together. You should pick one and use it alone. `ui-negative-number` is only an attribute to be used together with `ui-number-mask`.

**Comment by Sevensnake** [comment]
Is it possible to modify to use together?

**Comment by assisrafael** [comment]
It will be probably better if you use only `ui-percentage-mask` with the `ui-negative-number` attribute.
However, I am not sure if the `ui-percentage-mask` checks the presence of the `ui-negative-number` attribute. If not, a pull request implementing it will be very welcome.

**Comment by assisrafael** [comment]
Already available in the latest release.

**Comment by Sevensnake** [comment]
Ok. Small bug to fix. I will uninstall it then re add it.  The bug is to alert users first they do not have the latest nativescript cli. If not then it will say this but will not allow you to no longer update. Says it was done already.  Thanks.
