### ISSUE TITLE
Problem installing with bower and Angular 1.4.7

### ISSUE THREAD

**Issue by leandrocosta** [assisrafael/angular-input-masks#139]
<pre>
bower install angular-input-masks --save
bower angular-input-masks#*     cached https://github.com/assisrafael/bower-angular-input-masks.git#2.1.0
bower angular-input-masks#*   validate 2.1.0 against https://github.com/assisrafael/bower-angular-input-masks.git#*
bower angular#~1.3.16           cached https://github.com/angular/bower-angular.git#1.3.20
bower angular#~1.3.16         validate 1.3.20 against https://github.com/angular/bower-angular.git#~1.3.16
bower string-mask#~0.2.0        cached https://github.com/the-darc/string-mask.git#0.2.2
bower string-mask#~0.2.0      validate 0.2.2 against https://github.com/the-darc/string-mask.git#~0.2.0
bower br-validations#~0.2.4     cached https://github.com/the-darc/br-validations.git#0.2.4
bower br-validations#~0.2.4   validate 0.2.4 against https://github.com/the-darc/br-validations.git#~0.2.4
bower angular#^1.2.x            cached https://github.com/angular/bower-angular.git#1.4.8
bower angular#^1.2.x          validate 1.4.8 against https://github.com/angular/bower-angular.git#^1.2.x
bower angular#~1.x              cached https://github.com/angular/bower-angular.git#1.4.8
bower angular#~1.x            validate 1.4.8 against https://github.com/angular/bower-angular.git#~1.x
bower angular#1.4.7             cached https://github.com/angular/bower-angular.git#1.4.7
bower angular#1.4.7           validate 1.4.7 against https://github.com/angular/bower-angular.git#1.4.7
bower angular#>= 1.0.8          cached https://github.com/angular/bower-angular.git#1.4.8
bower angular#>= 1.0.8        validate 1.4.8 against https://github.com/angular/bower-angular.git#>= 1.0.8
bower angular#>=1.2.0           cached https://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.2.0         validate 1.4.8 against https://github.com/angular/bower-angular.git#>=1.2.0
bower angular#>1.0.6            cached https://github.com/angular/bower-angular.git#1.4.8
bower angular#>1.0.6          validate 1.4.8 against https://github.com/angular/bower-angular.git#>1.0.6
bower angular#>= 1.3.6          cached https://github.com/angular/bower-angular.git#1.4.8
bower angular#>= 1.3.6        validate 1.4.8 against https://github.com/angular/bower-angular.git#>= 1.3.6
bower angular#>=1.3.x           cached https://github.com/angular/bower-angular.git#1.4.8
bower angular#>=1.3.x         validate 1.4.8 against https://github.com/angular/bower-angular.git#>=1.3.x
bower angular#^1.3.0 || >1.4.0-beta.0           cached https://github.com/angular/bower-angular.git#1.4.8
bower angular#^1.3.0 || >1.4.0-beta.0         validate 1.4.8 against https://github.com/angular/bower-angular.git#^1.3.0 || >1.4.0-beta.0
bower                                        ECONFLICT Unable to find suitable version for angular
</pre>

##

**Comment by assisrafael** [comment]
This seems to be a problem with the pinned versions in your bower.json.

**Comment by rochapablo** [comment]
+1

**Comment by stevengiraldo** [comment]
+2

**Comment by assisrafael** [comment]
Bower is no longer supported.
