### ISSUE TITLE
Incompatible with angular 1.4.x

### ISSUE THREAD

**Issue by leandrolimasi** [assisrafael/angular-input-masks#142]
I have a problem with bower install when use angular 1.4.x

Error: Cannot assign to read only property 'toArray' of #<p>

Isn't compatible?

**Comment by assisrafael** [comment]
It probably is incompatible, take a look in the (README)[https://github.com/assisrafael/angular-input-masks#compatibility].

**Comment by leandrolimasi** [comment]
I solve the problem. 

The plugin have a prototype method "toArray". This name is very common and in my project I have a prototype method "toArray" too. 

The plugin should not use so common names in methods.

But works fine now. I'm use angular 1.4.8

Tanks
