### ISSUE TITLE
Evento ao completar a máscara

### ISSUE THREAD

**Issue by fndmiranda** [assisrafael/angular-input-masks#151]
Boa tarde, como eu poderia criar um evento que ao completar um campo ui-br-cep-mask fazer uma requisição passando o valor preenchido nesse campo? Para obter o endereço completo por exemplo.

**Comment by assisrafael** [comment]
You can write a custom directive that watches the viewValue or modelValue.

**Comment by fndmiranda** [comment]
Ok, thank you
