### ISSUE TITLE
Reverse input-mode

### ISSUE THREAD

**Issue by GVersluiss** [assisrafael/angular-input-masks#154]
Is it possible to switch the input-mode from left-to-right instead of right-to-left.

In example: when using "ui-money-mask" and I type "50" it shows "$0.50".
I think it would make much more sense when it shows "$50.00".

**Comment by assisrafael** [comment]
No, we do not have this feature.

**Comment by skarface** [comment]
+1 Welcome feature to implement.

**Comment by vincentfierant** [comment]
+1 This would be great.

**Comment by marcomafessolli** [comment]
Related with #144 and #118

**Comment by avlima** [comment]
+ 1

**Comment by assisrafael** [comment]
Duplicate of #118 (thank you @marcomafessolli)
