### ISSUE TITLE
input[type=number] throw e.replace is not a function 

### ISSUE THREAD

**Issue by moshfeu** [assisrafael/angular-input-masks#157]
I'm trying to using `ui-number-mask` on `input[type=number`. When I press on any number I'm getting 

> e.replace is not a function 

My html:

`<input type="number" data-ng-model="amount" data-ui-number-mask />`

[bin with the problem](http://output.jsbin.com/yinezi)

![untitled](https://cloud.githubusercontent.com/assets/3723951/12810788/0137877a-cb31-11e5-9f65-ad45341cec01.png)

Thanks

**Comment by assisrafael** [comment]
This library was built to work only on ```input[type=text]```.
