### ISSUE TITLE
Máscara telefone BR sem DDD ( ui-br-phone-number )

### ISSUE THREAD

**Issue by duraes** [assisrafael/angular-input-masks#164]
É possível usar a máscara de telefone sem o uso do DDD?
Ou que o preenchimento das casas comece de trás pra frente, um inverse=true ou algo equivalente a:
1
12
123
1234
1-2345
12-3456
123-4567
1234-5678
12345-6789

Obrigado!
##

**Comment by assisrafael** [comment]
Duplicate of #70
