### ISSUE TITLE
Reconhecer decimal antes de frações

### ISSUE THREAD

**Issue by filipepipeline** [assisrafael/angular-input-masks#165]
Olá, é difícil falar dessa funcionalidade. Mas queria saber se é possível em uma máscara de número, ao digitar 12, ele reconhecer o antes das frações? Pois atualmente caso eu queria digitar, 12, tenho que digitar 12.0. O que falo é ele começar a preencher pela dezena, não pelo decimal.

No aguardo, espero ter conseguido expressar minha dúvida.
##

**Comment by assisrafael** [comment]
No, such feature is not part of this lib.
A pull request if such behaviour is welcome.

**Comment by assisrafael** [comment]
Duplicate of #115
