### ISSUE TITLE
Aplicar máscara sem ser em um input

### ISSUE THREAD

**Issue by ricardotomim** [assisrafael/angular-input-masks#166]
É possível aplicar a máscara sem ser em um input?

exemplo: <h4>CPF: {{ partner.cpf  | filter:ui-br-cpf-mask }}</h4>

**Comment by assisrafael** [comment]
Take a look at: https://github.com/assisrafael/angular-input-masks#filters

**Comment by ricardotomim** [comment]
Muito obrigado assisrafael
