### ISSUE TITLE
US Phone numbers

### ISSUE THREAD

**Issue by kapilkale** [assisrafael/angular-input-masks#17]
Hi folks,

This is a lovely project. I forked it and made a slight adjustment for it to work for US phone numbers, as they're usually formatted "0 (000) 000-0000" or "(000) 000-0000". Perhaps worth considering having a different directive for such formats?

Cheers,
Kapil

**Comment by burakkilic** [comment]
Hi @kapilkale ;

I want to apply it for Turkish phone numbers since they are +90 (XXX) XXX-XX-XX . I think there should be a parameter to format.

**Comment by assisrafael** [comment]
us phone numbers implemented on #49
