### ISSUE TITLE
Delete last digit of ui-percentage-mask

### ISSUE THREAD

**Issue by ruisilva450** [assisrafael/angular-input-masks#174]
Hi, I was trying to use the ui-percentage-mask attribute but when I insert some number, I can't delete that number hitting backspace. 

The only way is to select the whole input content and then delete altogether.

This can be reproduced on the [main page](http://assisrafael.github.io/angular-input-masks/) where is used the ui-percentage-mask attribute.

**Comment by assisrafael** [comment]
You're right. This is a bug. If you can, please submit a pull request fixing this behaviour and implementing a test case for this scenario.

**Comment by nloding** [comment]
@assisrafael and @ruisilva450: I've run into this bug myself and just submitted a PR for it.

**Comment by nloding** [comment]
@assisrafael: Are you going to update the `2.2.0` tag, or release the fix as a new version down the road?
