### ISSUE TITLE
ui-money breaks if decimals are defined as a string

### ISSUE THREAD

**Issue by marcomafessolli** [assisrafael/angular-input-masks#180]
Hi there. 

`ui-money-type` breaks if decimals are defined as a string. 

Example code: 
```
<input ng-model="money" ui-money-mask="decimals" placeholder="Money" ng-init="money = 15.55">
<input type="text" ng-model="decimals" ng-init="decimals = 2" placeholder="Money decimals">
```
The problem seems to be at this line: https://github.com/assisrafael/angular-input-masks/blob/master/src/global/money/money.js#L17. The function `isNaN` returns `false` if the value is a "number" string (ex: `"1"`). When  creating a `new Array`, instead of creating a array with decimals plus 1 positions, it creates an array with one position with a concatenation between the decimals and 1 (ex: `new Array("31")`).

A suggestion is use `parseInt()` before it creates a new Array, allowing string as definition of decimals.

I tested with `percentage-mask` and `number-mask` and this problem doesn't happen.

**Comment by assisrafael** [comment]
Fixed by #181
