### ISSUE TITLE
Make as service/filter to format data in a controller

### ISSUE THREAD

**Issue by danieloprado** [assisrafael/angular-input-masks#188]
Just an idea, create a service to format the data on controller like:

as service:
`ngInputMasks.format("money", 15.5) // $ 15.50`

as filter:
`$filter('mask-money')(15.5) // $ 15.50`

and the directives use service to format the data.

**Comment by assisrafael** [comment]
Please check https://github.com/assisrafael/angular-input-masks#filters

**Comment by victorhazbun87** [comment]
https://github.com/assisrafael/angular-input-masks#filters that only covers BR, is there a US filter?
