### ISSUE TITLE
Placeholder não aparece com ui-number-mask

### ISSUE THREAD

**Issue by alinearielo** [assisrafael/angular-input-masks#189]
Oi!

Tentei usar placeholder em um input com ui-number-mask="2" porém não funciona, fica mostrando 0,00. Teria alguma maneira de manter o placeholder e só mascarar quando digita? Consegui usar placeholder por exemplo com a ui-date-mask.

Obrigada!

**Comment by alinearielo** [comment]
Acabei verificando que era um erro de model num retorno do sistema legado. ;D

**Comment by assisrafael** [comment]
I'm not sure if I understood your question, but placeholders are not affected by the input-mask, only the view and model values.
