### ISSUE TITLE
$scope value gets undefined (and can't be modified) for CPF, CNPJ masks

### ISSUE THREAD

**Issue by berbare** [assisrafael/angular-input-masks#190]
I'm on version 2.0.0

If I start a `$scope` object like this:

    $scope.partner = {cpf: someVar};

Then the input below is pre-filled with `someVar`, but changing it in the slightest will delete the `$scope.partner.cpf` variable (inspecting, it shows as `undefined`, and using `{{partner.cpf}}` on the HTML renders nothing. Even `ngChange` won't trigger anymore on the input (only once, and the value will be `undefined` already).

    <input type="text" placeholder="CPF" ng-model="partner.cpf" ui-br-cpf-mask>

I found issue #110 to be similar but I'm not sure if it's related. Tried changing it to the `ui-br-phone-number` directive instead and it works fine. But both `ui-br-cpf-mask` and `ui-br-cnpj-mask` lead to this problem.

**Comment by assisrafael** [comment]
What is the type of your data? Number or String?
Which angular version you are using?

**Comment by ichagas** [comment]
Same here. I am getting undefined when try to get the value in the Controller 

### View/HTML
`<input type="text" ng-model="data.amount" ui-money-mask="2" ng-change="onChange('amount')">`

### Controller
```
$scope.onChange = function (action, value) {
  amount = $scope.data.amount;
  console.log('value: ' + value)  // <- getting undefined
}
```

Angular version: v1.3.20

Is that possible use ng-change directive with the ui-masks?

**Comment by berbare** [comment]
@assisrafael string type, and I'm using angular 1.3.15

**Comment by assisrafael** [comment]
Can you build a live demo (plunker, etc) to reproduce your error?

**Comment by ichagas** [comment]
I believe I found the issue, it may be a bug for this scenario.

### Scenario
I am using `pattern="\d*"` into the <input> for force the numeric keyboard in iPhone.

`<input type="text" pattern="\d*" ng-model="data.amount" ui-money-mask="2" ng-change="onChange('amount')">`

I reproduced the error in CodePen **with** and **without** the `pattern`.

### See CodePen
[](http://codepen.io/igorchagas/pen/GZLWey)

Thanks for your work and +1 star for you.

**Comment by rcrodrigues** [comment]
@berbare perhaps the cpf number you'ŕe typing down is not being validated?
Make sure your CPF is valid. For this, you can use a service like this one http://www.controlenanet.com.br/validacnp/valida_cnp.php

**Comment by felippeduarte** [comment]
Had this issue here. Probably your CPF ins't valid. There is any way to remove or toggle validation? If not, I'm going to propose this change.

**Comment by kristiantenfen** [comment]
Resolved?

**Comment by brunoksato** [comment]
CNPJ same bug

**Comment by detinho** [comment]
@ichagas your pattern should deal with the other symbols ($ and .(dot)). I changed your CodePen with a pattern="[\$ \d|\.]*" and it worked!
The only way I got an undefined was with invalid values, but I think it's the expected behavior. I think the best bet here is @felippeduarte's idea to be able to toggle the validation off.

**Comment by berbare** [comment]
Hey, sorry for the late response. I'm not sure why but the issue's not bothering anymore. I think it was indeed related to invalid model values, but I can't reproduce the exact problem anymore.

I'm more familiar now with angular and its directives, so I get why it showed up as undefined. Still, I'm now able to overwrite this undefined value and eventually reach a valid input (changing the model property as expected). Back when I opened this issue, I was unable to do this overwriting in case it ever got undefined. That's what I can't reproduce anymore, and I believe the current behavior is as expected.
