### ISSUE TITLE
Bower package conflicts with angular#1.5.7

### ISSUE THREAD

**Issue by jcvandamme** [assisrafael/angular-input-masks#197]
Bower package conflicts with angular 1.4.x and 1.5.x, but there are no apparent issues when using the input-masks directives with the newer versions of angular. 

![inputmasksconflict](https://cloud.githubusercontent.com/assets/8193052/16170941/38b65fd6-3563-11e6-879d-548d26a8cea1.PNG)

**Comment by assisrafael** [comment]
Please submit a pull request to fix this problem at: https://github.com/assisrafael/bower-angular-input-masks

**Comment by assisrafael** [comment]
Fixed declared dependency of bower.json in version 1.4
