### ISSUE TITLE
Instalar o Input Masks sem npm

### ISSUE THREAD

**Issue by rhuanbarreto** [assisrafael/angular-input-masks#200]
Como faço para utilizar o angular-input-masks sem usar o npm, ou seja, somente chamando uma tag script e colocando em uma pagina html?

**Comment by thekaduu** [comment]
Você pode utilizar o bower se preferir ou clonar o repositório e fazer com tag script memso.

Com Bower ficaria assim 

`$ bower install angular-input-masks`

**Comment by rhuanbarreto** [comment]
Não estou usando node.js
Eu queria poder baixar e integrar em uma tag script mesmo.

**Comment by detinho** [comment]
Em nosso projeto baixamos usando o bower em qualquer diretório e copiamos o angular-input-masks-standalone.min.js para o nosso projeto.
Aí usamos normalmente.

**Comment by thekaduu** [comment]
Exato, tu pode fazer isso mesmo @rhuanbarreto, no meu fork eu coloquei os arquivos que vc vai precisar caso não queria realmente utilizar o **NodeJs**.

Bem, ta ai o link [standalone.min.js](https://github.com/thekaduu/angular-input-masks/blob/master/angular-input-masks-standalone.js). Nesse fork ai bem de cara vc vai ver o de mask br e o maks us também, já fiz o pull request, provavelmente daqui a pouco vai estar direto aqui no repositório também.

**Comment by assisrafael** [comment]
Or download the files manually from https://github.com/assisrafael/bower-angular-input-masks
