### ISSUE TITLE
Adicionar Mascara Condicionalmente

### ISSUE THREAD

**Issue by rhuanbarreto** [assisrafael/angular-input-masks#202]
Queria poder adicionar condicionalmente as mascaras no input, dependendo de uma propriedade de u objeto.

Tentei o seguinte:

`<input type="text" class="form-control" ng-model="indicador.meta" ng-disabled="indicador.conta" ng-attr-ui-number-mask="{{indicador.formato == 2 || undefined}}" ng-attr-ui-percentage-mask="{{indicador.formato == 4 || undefined}}" ng-attr-ui-money-mask="{{indicador.formato == 3 || undefined}}" />`

**Comment by thekaduu** [comment]
Já pensou em usar o ng-if com 1 input pra cada mask?
`
<input type="text" class="form-control" ng-model="indicador.meta" ng-disabled="indicador.conta" ng-attr-ui-number-mask  ng-if="indicador.formato == 2"/>`

e assim  para cada mask

**Comment by rhuanbarreto** [comment]
Obrigado! Não fica tão enxuto mas resolve!
