### ISSUE TITLE
ui-br-cpfcnpj-mask undefined value

### ISSUE THREAD

**Issue by vaneves** [assisrafael/angular-input-masks#209]
Hello, 

I tried use the mask `ui-br-cpfcnpj-mask`, but return undefined value on variable. I tried use the event `$scope.$watch`, but return undefined value on params. Using `ui-br-cnpj-mask` or `ui-br-cpf-mask` it works normally.

Thanks!

**Comment by vaneves** [comment]
Sorry. It's working perfectly. Only gives undefined and did not trigger the event when the CPF/CNPJ is invalid.

**Comment by VitorHFLopes** [comment]
Nice @vaneves ! Thanks for the explanation! I didn't  know that the mask could solve this too

**Comment by ciroanacleto** [comment]
I've noted when the cpf or cnpj is invalid the model is undefined. Is there a way to disable validation and allow just formatting ?

**Comment by bridge-soft** [comment]
ng-model-options="{allowInvalid: true}" in input field
