### ISSUE TITLE
adding ui-hide-space attribute not removing space between [Number] and [%]

### ISSUE THREAD

**Issue by zubairshaikh** [assisrafael/angular-input-masks#215]
Hi,

I have added below given attributes to a input type text but the space between [Number] and [%] is still there. It is not getting removed. Appreciate if any one can help to fix this issue.

<input type="text" name="percentage" ng-model="vm.percentage" ui-percentage-mask="0" ui-percentage-value ui-hide-space min="0" max="100" required class="form-control" />

Regards,
Zubair Shaikh

**Comment by assisrafael** [comment]
Check if 2.5.0 solves your problem.
If not reopen this issue.
