### ISSUE TITLE
Ionic mobile: erro durante digitação/error while typing 

### ISSUE THREAD

**Issue by lopesricardo** [assisrafael/angular-input-masks#224]
Olá,

Está ocorrendo um erro ao usar o componente no mobile (no IONIC).
Exemplo: meu campo é conforme abaixo:

`<input  type="text" name="field" ng-model="meuCampo" ui-number-mask="3">`

Quando eu digito os valores, exemplo: 12345, o campo fica com o valor "123,54". Isso está correto.
Mas se eu digitar o sexto valor, ou seja, o "6", ele fica "12,345,123.456".
Eu apenas digitei o sexto caracter e ele ficou desta forma, com todos esses números.
Alguém sabe como resolver isso?
Obrigado

Hi,
It's ocurring an error when I used the component into mobile (in IONIC).
Example: my field is like below:

`<input` type="text" name="field" ng-model="myField" ui-number-mask="3">`

When I type the values, example: 12345, the field is "123,54". This is right.
But if I type the sixth value, that is "6", the field is " 12,345,123.456".
I just typed the sixth value and the field was so, with a lot of numbers.
Does anyone know how to fix it?
Thanks

**Comment by lopesricardo** [comment]
Olá pessoal,

O problema era o Teclado Inteligente do Android 6, especificamente, a função autocomplete.
Desabilitei a função e o problema parou.
No iOS ou em versões anteriores do Android o problema não ocorre.

Obrigado.

The trouble was the Smart Keyboard of Android 6.
When I disabled the function, the trouble is over.
On iOS or previow versions of Android, this trouble don't happens.

Thanks.

**Comment by assisrafael** [comment]
Closing since you found a workaround.
Reopen this issue if necessary.
