### ISSUE TITLE
[Question] Set currency symbol and decimal separator in money mask

### ISSUE THREAD

**Issue by ignamiguel** [assisrafael/angular-input-masks#226]
Hi,
Is it possible to change the currency symbol and the decimal separator in money-mask?
I checked the release demo and commented the tag `angular-locale_pt-br.js` that uses the R$ symbol and now it is using just $ symbol.
But I also need colon decimal separator instead of dot, like this:
$ 1.234,56

Thanks in advance.
Greetings
##

**Comment by Yoshi9143** [comment]
You can set the currency symbol using the ` currency-symbol="$"` in your directive. Replace "$" with your symbol of choice. https://github.com/assisrafael/angular-input-masks/pull/203

Not sure of decimal separator

**Comment by ignamiguel** [comment]
Hi @Yoshi9143,

Yes, I've changed this [config file](https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.2.5/angular-locale_pt-br.js) used in demo/index.html and set there currency symbol and the decimal separator.

Thanks 👍
