### ISSUE TITLE
Invalid CPFs passing as valid

### ISSUE THREAD

**Issue by ivanhtp** [assisrafael/angular-input-masks#227]
The CPFs numbers below are invalid by definition but the module show them as valid:

111.111.111-11
222.222.222-22
333.333.333-33
444.444.444-44
555...

The problem happens on demo as well
![captura de tela 2016-10-20 as 2 29 25 pm](https://cloud.githubusercontent.com/assets/126082/19568763/a1e1a0cc-96d1-11e6-917c-79507d578050.png)
##

**Comment by ivanhtp** [comment]
![captura de tela 2016-10-20 as 2 29 25 pm](https://cloud.githubusercontent.com/assets/126082/19568763/a1e1a0cc-96d1-11e6-917c-79507d578050.png)

**Comment by brunobastosg** [comment]
This is validation is performed by [br-validations](https://github.com/the-darc/br-validations).

According to [this commit](https://github.com/the-darc/br-validations/commit/67c6c3c4a6b197edae16091595eeab4141ca31d1), this was fixed two years ago.

Maybe this project is using an older version.

**Comment by assisrafael** [comment]
Already fixed in latest version.
