### ISSUE TITLE
Mascara CPF Android 4.2

### ISSUE THREAD

**Issue by ronaldogaraujo** [assisrafael/angular-input-masks#228]
Boa noite senhores ...

Testei o plugin à partir do Android 4.4 e o mesmo funcionou 100%.

Quanto fui fazer o teste no Android 4.2 na digitação do 4º digito para frente a mascara se perde e o usuário não consegue informar o CPF de forma correta, tendo que toda hora posicionar o cursor na última posição para continuar digitando.

Alguém já enfrentou esse problema ?

Obrigado

Ronaldo Araujo
##

**Comment by jayrmotta** [comment]
Relacionado https://github.com/assisrafael/angular-input-masks/issues/242

**Comment by jayrmotta** [comment]
Não conseguimos reproduzir no iPhone.

Percebemos que o comportamento ocorre exatamente quando um caracter estático da máscara é inserido, então suspeitamos da lib de máscara, mais especificamente algo próximo dessa função:

https://github.com/the-darc/string-mask/blob/master/src/string-mask.js#L73

**Comment by jayrmotta** [comment]
O problema não é relacionado a biblioteca, é mais um problema do Angular com certos navegadores.

Segue um issue do StackOverflow relacionado: http://stackoverflow.com/questions/22940346/preserving-cursor-position-with-angularjs

A sugestão do pessoal é usar a API [HTMLInputElement.setSelectionRange()](https://developer.mozilla.org/pt-BR/docs/Web/API/HTMLInputElement/setSelectionRange) embora o suporte dele ainda não seja difundido.

**Comment by jayrmotta** [comment]
Já existe um pull request com a solução: https://github.com/assisrafael/angular-input-masks/pull/211

Ajuda aí @assisrafael 😄

**Comment by LauroRafael** [comment]
Eu estava com o mesmo problema ao inserir cpf ou cnpj o cursor pulava para depois do ponto e antes do número digitado.

RESOLVI dessa forma:

<input name="nome_campo" value="seu_valor" **onkeydown="this.selectionStart = this.value.length; this.selectionEnd = this.value.length;"**>

**Comment by marcoshmendes** [comment]
@LauroRafael Sua solução funcionou aqui. Valeu

**Comment by marcosvc84** [comment]
@LauroRafael utilizando a sua solução estou conseguindo digitar os 6 primeiros dígitos do cpf, depois apaga o que havia digitado, sabe o que pode ser?

**Comment by LauroRafael** [comment]
@marcosvc84 Opa, blz...
Não consegui emular esse problema que está acorrendo aí no seu caso.
Essa solução que eu havia postado, eu estava usando em um app onde o input aceita CPF ou CNPJ no mesmo campo. 
Você colocando apenas o que está em negrito no seu input, não resolveu??

> `onkeydown="this.selectionStart = this.value.length; this.selectionEnd = this.value.length;"`

**Comment by marcosvc84** [comment]
@LauroRafael o problema é que eu estava utilizando o type="number" e ocorria este problema. O que fiz e resolveu foi usar essa directive que segue e, para forçar o uso do teclado numérico coloquei no html desta forma: type="text" onfocus="(this.type='tel')"    . Tive que usar o tel pois com o number não funcionou

app.directive('input', input);
function input($timeout) {
  return {
    restrict: 'E',
    link: function ($scope, $element, $attrs) {
      $element.bind('keydown', function ($event) {
        $timeout(function () {
          $event.target.selectionStart = $event.target.value.length;
          $event.target.selectionEnd = $event.target.value.length;
        });
      });
    }
  };
}

**Comment by assisrafael** [comment]
Duplicate of #104
