### ISSUE TITLE
IE do Tocantins

### ISSUE THREAD

**Issue by edigomes** [assisrafael/angular-input-masks#231]
Seguinte IE não é válida para TO: 29.380.745-0, a lib não reconhece os pontos nem o dígito verificador, se indicar como resolver faço pull request!

Att.

**Comment by detinho** [comment]
@edigomes as máscaras estão aqui: https://github.com/assisrafael/angular-input-masks/blob/master/src/br/inscricao-estadual/ie.js
As validações estão no projeto https://github.com/the-darc/br-validations. Neste caso seria interessante checar se a validação já está funcionando na versão 0.3.0 da br-validations, visto que este projeto está usando a versão 0.2.4.

**Comment by assisrafael** [comment]
The latest version is alreary using the latest version of br-validations.
