### ISSUE TITLE
jQuery Dependency throws Uncaught Error during testing

### ISSUE THREAD

**Issue by sirhodes** [assisrafael/angular-input-masks#236]
I'm using Karma as a test runner, here is the output from the console to help debug. 
![jQuery dependency not satisfied](https://cloud.githubusercontent.com/assets/5307413/20542202/9a04eafa-b0ce-11e6-9936-960d20bfe7a1.jpg).

I'm using the standalone build, v2.3.0. Works great in-app, but am unable to run tests due to this error.

Things I've tried that did not work:
+ adding external (CDN) jQuery script reference to the files that are loaded
+ installing through jquery as a dependency through bower, then through npm (neither)

Any help is appreciated.

**Comment by assisrafael** [comment]
This seems unrelated to this library.
