### ISSUE TITLE
Como executar a demo (how to run the demo)

### ISSUE THREAD

**Issue by crivano** [assisrafael/angular-input-masks#239]
Parabéns pelo excelente trabalho!

Estou tentando executar a versão mais nova (2.5.0) e sempre dá erros do tipo: 

```
TypeError: Cannot set property 'date' of undefined
```

Agora tentei executar a própria demo e o erro é o mesmo. Veja a imagem anexa.

![angular_mask_demo_and_index2_html](https://cloud.githubusercontent.com/assets/4137623/20729006/72ea7162-b667-11e6-9942-e0d63c9682e4.png)

Será que pode me indicar o que estou fazendo errado?

Muito obrigado.

**Comment by assisrafael** [comment]
You can run the demo using the following command: `npm run demo` then you navigate to the url `localhost:9090/demo/index.html`
