### ISSUE TITLE
Problemas na máscara de ui-br-phone-number

### ISSUE THREAD

**Issue by laurindo** [assisrafael/angular-input-masks#240]
Ao recuperar o valor salvo, está sendo adicionado o valor +55 dentro do DDD (85) por exemplo.
Essa é a forma como estou pegando o valor.

`<input type="text"
   name="telefone"
   ui-br-phone-number
   placeholder="Digite aqui"
   ng-model="vm.contato.telefone" />`

Depois que salvo no banco o valor fica:
85991568956

Quando tento recuperar do banco e imprimir com a mascara, está ficando assim:
(55)85991-5689

Alguém com esse problema?

**Comment by assisrafael** [comment]
The mask uiBrPhoneNumber now supports the country prefix. Check the latest version.

**Comment by matheusnicolas** [comment]
Tem como utilizar sem o country code?
