### ISSUE TITLE
Error: Cannot find module 'string-mask'

### ISSUE THREAD

**Issue by MichelMiola** [assisrafael/angular-input-masks#241]
> Uncaught Error: Cannot find module 'string-mask'(…)
> lib.js:14341 Uncaught Error: [$injector:nomod] Module 'br.com.paripassu.directives' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.(…)
> lib.js:3883 Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:(…)

Version: 

> "angular-input-masks": "v2.5.0"

Dependency manager: bower

**Comment by samiraguiar** [comment]
I've got a similar issue.
In my case I get `Uncaught TypeError: StringMask is not a constructor` when using the standalone script, version 2.5.0.

**Comment by thorne51** [comment]
@MichelMiola What was your solution to this issue?

**Comment by williamknn** [comment]
@MichelMiola ?

**Comment by MichelMiola** [comment]
It was an internal problem even in the case only using standalone already official.
