### ISSUE TITLE
Problemas com a máscara de CPF

### ISSUE THREAD

**Issue by filipimosquini** [assisrafael/angular-input-masks#242]
Boa tarde a todos,

Quando eu digito o CPF, o cursor parece se perder e acaba bagunçando todo o CPF digitado.

Percebi que quando o cursor passa por algum ponto ou traço da máscara, em vez de o cursor se posicionar a direita do último número digitado, o cursor se posiciona a esquerda gerando o problema.

Alguém já passou por esse problema?

**Comment by diegocvigil** [comment]
Estou com o mesmo problema. 

Ainda não encontrei a solução

**Comment by brgenius** [comment]
+1

**Comment by jayrmotta** [comment]
Segue o pull request com a solução: https://github.com/assisrafael/angular-input-masks/pull/211

**Comment by wcustodio** [comment]
O problema ainda continua. Alguma solução?

**Comment by felulo** [comment]
The issue was solved using input with type="tel". It was tested in Samsung Keyboard, GBoard and Android Keyboard 4.4.4.

The problem was the keyboard response, if input's type was text, the keyboard change between alphanumeric keyboard and numeric keyboard. That behaviour breaks the moment when the code got the cursor position and set.

After that change, the keyboard not change and stay on numeric keyboard fixing the issue.

**Comment by vilasboas** [comment]
>The issue was solved using input with type="tel".

Doesn't work for me

**Comment by fernandoghisi** [comment]
Neither for me.

**Comment by GuilhermeMaia91** [comment]
Resolvi o problema com o seguinte código no HTML:
`<input autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" />`

**Comment by camilaazuma** [comment]
@felulo worked for me, thx 😄

**Comment by LauroRafael** [comment]
Eu estava com o mesmo problema ao inserir cpf ou cnpj o cursor pulava para depois do ponto e antes do número digitado.

RESOLVI dessa forma:

<input name="nome_campo" value="seu_valor" **onkeydown="this.selectionStart = this.value.length; this.selectionEnd = this.value.length;"**>

**Comment by fernandoghisi** [comment]
@LauroRafael, eu estava batendo cabeça com isso até agora e já tinha tentado várias possíveis soluções que eu tinha encontrado nas minhas pesquisas e, justamente hoje, eu comecei a testar outros componentes de máscara e descobri que o problema ocorre com vários deles e especificamente no Android (a partir de uma certa versão do navegador).

Mas parece que esse teu "workaround" funciona, de certo modo, deixando bem melhor do que estava antes - apesar de ter alguns detalhes não deixarem a experiência 100% (como o fato do cursor ainda ficar posicionado errado, mesmo que depois o caractere digitado fique no lugar correto).

Outro ponto é que não é uma boa prática misturar eventos nativos com eventos do Angular; mas, como minimizou o problema e é simples de fazer, seria uma boa solução temporária até se conseguir uma solução definitiva. Valeu pela dica!

Por fim, vai a minha dica: dentre as outras bibliotecas de máscara que testei, uma acabou não apresentando esse problema (https://github.com/angular-ui/ui-mask), pelo menos na digitação sequencial (embora também apresente se der backspace até encontrar um separador da máscara) e me parece a melhor opção enquanto o problema não é resolvido. Só teria que adaptar o código do app, pois ela funciona um pouco diferente e tem alguns macetes pra atingir os mesmos resultados.

**Comment by camilaazuma** [comment]
@fernandoghisi Eu apliquei a solução do PR #211 e funcionou perfeitamente. Inclusive o app já está em produção e não houve nenhum report até agora

**Comment by leuterio** [comment]
This worked for me:
Inside the input tag add:
autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"

**Comment by marcosvc84** [comment]
@camilaazuma como você aplicou esta solução? Não consegui instalar com a aleração realizada

**Comment by leuterio** [comment]
@marcosvc84  tenta isso: 
Dentro da tag input adicione os atributos:
autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"

**Comment by marcosvc84** [comment]
@leuterio eu havia testado essa sua solução mas não resolveu. O que funcionou pra mim foi utilizar a directive que segue. Além da Directive utilizei na tag type="text" placeholder="CPF" onfocus="(this.type='tel')". Se no onfocus uso o type number não funciona a máscara, mas usando o tel funcionou, para forçar a usar o teclado numérico do Android.

.directive('input', input);
function input($timeout) {
  return {
    restrict: 'E',
    link: function ($scope, $element, $attrs) {
      $element.bind('keydown', function ($event) {
        $timeout(function () {
          $event.target.selectionStart = $event.target.value.length;
          $event.target.selectionEnd = $event.target.value.length;
        });
      });
    }
  };
}

**Comment by camilaazuma** [comment]
@marcosvc84 Eu já tinha baixado o repositório na minha máquina, então apliquei o trecho modificado direto. Como era um arquivo só, não vi necessidade de baixar o fork com a alteração e reinstalar todas as dependências e etc.
Qual foi o problema que você teve?

**Comment by marcosvc84** [comment]
@camilaazuma eu havia instalado o repositório utilizando o bower, vou precisar baixar todo o repositório na minha máquina com a alteração e utilizar o bower a partir deste código local, estava instalando a partir do repositório remoto

**Comment by camilaazuma** [comment]
@marcosvc84 Isso. Então, na vdd o que você fez não foi instalar o repositório. O bower só inclui a biblioteca no __seu projeto__, são os arquivos de distribuição. A correção é feita no projeto __da biblioteca__.

Primeiro clona o repositório na sua máquina e depois dá uma olhada no readme do projeto. Tem uma seção _Build_ lá. Mas basicamente você instala as dependências, aplica a correção, faz um build e coloca os arquivos no seu projeto

**Comment by marcosvc84** [comment]
@camilaazuma muito obrigado Camila, vou fazer este procedimento, por enquanto estou usando uma solução de um directive que você inclusive melhorou para usar apenas no campo de cpf. Mas vou tentar utilizar a desta PR. Muito obrigado

**Comment by assisrafael** [comment]
Duplicate of #104

**Comment by PierreBosch** [comment]
@felulo Resolveu para mim (Solved to me)
