### ISSUE TITLE
Directive doesn't work when inside ng-repeat

### ISSUE THREAD

**Issue by lucianolucianoluciano** [assisrafael/angular-input-masks#248]
I was facing a problem in an app where my view was cleaning the data coming from the server. As it turns out, the mask directive was responsible for it in a way I can not understand.

I was able to replicate this bug just using the _ng-repeat_ directive inside a _input_ field and using the mask directive. It doesn't work properly, only placing the separators. _eg: <input data-mask="19/29/9999"_ will create a input where if I type '11111111' it will appear like '11/11/1111' but it doesn't block typing other character, like 'a' or '('... 

But my major problem is that when the data comes back from the server, this _ng-repeat inside_ mask directive is setting my attribute to undefined.

**Comment by frossetto** [comment]
@luciannojunior were you able to find a workaround for this issue? I'm facing the same problem.
