### ISSUE TITLE
Rename node_modules into libs

### ISSUE THREAD

**Issue by vitorcamachoo** [assisrafael/angular-input-masks#254]
Hii, What's the reason to leave node_modules inside src/ ? I'm having problems to compile using Webpack 2.

Example. 

![image](https://cloud.githubusercontent.com/assets/20595956/22983597/80763b84-f39a-11e6-96a9-1f0b9d72e7be.png)

**Comment by danieloprado** [comment]
Same problem with electron-builder

**Comment by eseliger** [comment]
@assisrafael  Could you push the fix to npm? :)
