### ISSUE TITLE
Caret position changed while input first value

### ISSUE THREAD

**Issue by akashs1706** [assisrafael/angular-input-masks#256]
Hello, 
First of all, nice plugin.
i am using this library in my ionic application for product amount formatting.
It works fine when i test the application in ionic-lab on chrome browser, the cursor position remains at the end always.
But when i use the application in mobile as android build then on inputting amount, at the very first input it changed the caret to starting position from end position. Please resolve this.

**Comment by ricardovalezan** [comment]
Same problem here, after android update

**Comment by vilasboas** [comment]
Same problem here too

**Comment by devfelipereis** [comment]
Same problem here! Android version 5.0.1.

**Comment by brgenius** [comment]
+1

**Comment by Connor-Knabe** [comment]
Seems to be happening on Chrome Browser 57 on Android 6.0.1 too.  

Any updates on this issue?

**Comment by devfelipereis** [comment]
I have something!

I don't know why but for me it was the device I was testing my app.
It's a Galaxy S4 GT-19505 Android 5.0.1.

**Comment by Connor-Knabe** [comment]
@devfelipereis any ideas on where in the code the problem is occurring? I'm looking into this and will hopefully get a pull request in if I fix it.

**Comment by Connor-Knabe** [comment]
This seemed to fix it for me....
[](https://github.com/assisrafael/angular-input-masks/issues/104#issuecomment-156538954)

**Comment by Connor-Knabe** [comment]
Adding the timeout from this [comment](https://github.com/assisrafael/angular-input-masks/issues/104#issuecomment-156538954) seemed to fix the issue for me :+1:

**Comment by devfelipereis** [comment]
@Connor-Knabe Not yet. I'm a little bit busy to try to find it. If I find something I'll post here.

**Comment by AHBZero** [comment]
Maybe be useful:
```
function setCaretPosition(input, pos) {
                                if (!input)
                                    return 0;
                                if (input.offsetWidth === 0 || input.offsetHeight === 0) {
                                    return; // Input's hidden
                                }
                                if (input.setSelectionRange) {
                                    if (isFocused(iElement[0])) {
                                        input.focus();
                                        input.setSelectionRange(pos, pos);
                                    }
                                }
                                else if (input.createTextRange) {
                                    // Curse you IE
                                    var range = input.createTextRange();
                                    range.collapse(true);
                                    range.moveEnd('character', pos);
                                    range.moveStart('character', pos);
                                    range.select();
                                }
                            }
```
