### ISSUE TITLE
Paste value greater than maxlength

### ISSUE THREAD

**Issue by andreas-andrade** [assisrafael/angular-input-masks#261]
Consider the input below:

`<input type="text" ng-model="vm.value" ui-number-mask="2" maxlength="5" ui-hide-group-sep name="componentName" />`

I can digit a number with the format "99,99". If I paste the value "12345", the component gets the value "123,45", but it should prevent the user input such value.

**Comment by assisrafael** [comment]
You can implement such behavior with a custom directive.
