### ISSUE TITLE
file angular-input-masks-standalone.min.js is missing.

### ISSUE THREAD

**Issue by sonicwong** [assisrafael/angular-input-masks#262]
file angular-input-masks-standalone.min.js is missing.
Any body can help?

**Comment by Maximaximum** [comment]
Why has this issue been closed?

I can't find this file as well!

**Comment by sonicwong** [comment]
@Maximaximum 
when u run "npm install --save angular-input-masks",
you will got the file inside "node_modules\angular-input-masks\releases" folder.
