### ISSUE TITLE
Problema ao atribuir programaticamente um valor ligado a um input com máscara 

### ISSUE THREAD

**Issue by fernandoghisi** [assisrafael/angular-input-masks#264]
Utilizando a máscara de CPF/CNPJ em um input com um ngModel, conforme abaixo, se digitar o valor do CPF/CNPJ, a máscara funciona corretamente e uma outra diretiva utilizada como validador informa que o campo está válido (essa diretiva foi suprimida aqui, mas ela simplesmente faz a validação sobre o valor numérico presente no model - que não armazena a máscara).

`<input name="cpf" type="tel" ng-model="usuario.cpf" **ui-br-cpfcnpj-mask**>`

O problema ocorre quando tento apresentar o formulário já preenchido, atribuindo um valor à variável no $scope ligada ao ngModel desse input ($scope.usuario.cpf).

Se atribuo o cpf numérico (sem a máscara) - que é o correto, pois a a máscara é apenas visual - o seguinte erro estoura no código da máscara:
`TypeError: t.replace is not a function at Object.clearValue (angular-input-masks-standalone.min.js:2) at Array.<anonymous> (angular-input-masks-standalone.min.js:3)`

Se atribuo o cpf com máscara (utilizando uma função auxiliar, que gera o string com máscara), "funciona"; mas o campo do formulário fica inválido, pois primariamente ele espera somente dígitos (sem contar a verificação da validade do CPF) e o valor vai conter os caracteres da máscara.

Alguma solução simples para isso, ou seria preciso alterar o código da diretiva da máscara?

**Comment by fernandoghisi** [comment]
Trocando para o arquivo não minificado, o erro ocorre na linha 4585 ("rawValue.replace"):

`var cpfPattern = new StringMask('000.000.000-00');

module.exports = maskFactory({
	clearValue: function(rawValue) {
		return rawValue.replace(/[^\d]/g, '').slice(0, 14);
	},`

**Comment by vinigarcia87** [comment]
Mesmo problema com data e CEP

**Comment by rafaeldev** [comment]
+1 - Alguém conseguiu resolver isso?

**Comment by victorldomingues** [comment]
+1
