### ISSUE TITLE
Problema com sequência de digitação dos números no Chrome para Android

### ISSUE THREAD

**Issue by lennonjesus** [assisrafael/angular-input-masks#266]
No **Google Chrome Mobile para Android** a máscara **não** respeita a ordem de digitação dos números.

Como exemplo, usando ```ui-br-phone-number```, a digitação dos números ```12345678900``` fica formatado como ```(23) 67890-0541``` e com model value ```23678900541```.

Pode ser reproduzido em [http://assisrafael.github.io/angular-input-masks/](http://assisrafael.github.io/angular-input-masks/)

![assisrafael github io-angular-input-masks- nexus 5](https://cloud.githubusercontent.com/assets/36691/24332313/e219394c-121a-11e7-8179-426c75eda0d6.png)

**Comment by GuilhermeMaia91** [comment]
Estou com o mesmo problema...Alguma solucação?

**Comment by DfKimera** [comment]
Consegui reproduzir só em alguns aparelhos Samsung. Acredito que seja relacionado à versão do WebView disponível, pois ocorre também em aplicativos híbridos com Cordova.

**Comment by lennonjesus** [comment]
Consigo reproduzir o problema em aparelhos Samsung, Motorola e Asus.

**Comment by danilloborges** [comment]
Confirmando reprodução no Sansung, Motorola e Asus.

**Comment by brunoksato** [comment]
up

**Comment by AHBZero** [comment]
Maybe be useful:
```
function setCaretPosition(input, pos) {
                                if (!input)
                                    return 0;
                                if (input.offsetWidth === 0 || input.offsetHeight === 0) {
                                    return; // Input's hidden
                                }
                                if (input.setSelectionRange) {
                                    if (isFocused(iElement[0])) {
                                        input.focus();
                                        input.setSelectionRange(pos, pos);
                                    }
                                }
                                else if (input.createTextRange) {
                                    // Curse you IE
                                    var range = input.createTextRange();
                                    range.collapse(true);
                                    range.moveEnd('character', pos);
                                    range.moveStart('character', pos);
                                    range.select();
                                }
                            }
```

**Comment by bsysop** [comment]
Alguma novidade?

**Comment by rafakwolf** [comment]
@bsysop , penei bastante com esse problema também, solucionei fazendo uma outra diretiva que adiciono onde preciso resolver:

Eis o método link da diretiva:
`    link = (scope: ng.IScope, elem: JQuery, attrs: ng.IAttributes, ngModel: ng.INgModelController) => {
        elem.bind('keydown', ($event: JQueryEventObject) => {
            if ($event.keyCode !== 8) {
                this.$timeout(() => {
                    let caretPos = (<HTMLInputElement>$event.target).value.length;

                    // Método caret é do jquery.maskedinput
                    // por isso ele é uma dependência
                    elem.caret(caretPos, caretPos);
                });
            }
        });
    }`

espero que ajude

**Comment by bsysop** [comment]
kkkk @rafakwolf valeu demais,

Segue a implementação que eu adaptei de outro parceiro, verifica se o input e qualquer um dos que tenham o atributo de mascara, e caso for, trata do meu jeito mais ou menos que voce faz.

Abs.

    .directive('input', function input($timeout) {
        return {
            restrict: 'E',
            link: function ($scope, $element, $attrs) {
                if ($attrs.$attr.uiBrCpfMask ||
                    $attrs.$attr.uiBrBoletoBancarioMask ||
                    $attrs.$attr.uiBrCepMask ||
                    $attrs.$attr.uiBrCnpjMask ||
                    $attrs.$attr.uiBrCpfcnpjMask ||
                    $attrs.$attr.uiBrIeMask ||
                    $attrs.$attr.uiNfeAccessKeyMask ||
                    $attrs.$attr.uiBrCarPlateMask ||
                    $attrs.$attr.uiBrPhoneNumber) {
                    $element.bind('keydown', function ($event) {
                        if ($event.keyCode != 8) {
                            $timeout(function () {
                                $event.target.selectionStart = $event.target.value.length;
                                $event.target.selectionEnd = $event.target.value.length;
                            });
                        }
                    });
                }
            }
        };
    })

**Comment by assisrafael** [comment]
Duplicate of #104

**Comment by lennonjesus** [comment]
@assisrafael, só para documentar, o problema que relatei não foi detectado no Ionic. Foi em uma página web simples, acessada via Google Chrome. :)

**Comment by betorobson** [comment]
@lennonjesus , coloque o input com type="tel", isso vai funcionar perfeitamente

**Comment by lennonjesus** [comment]
Perfeito, @betorobson! Funcionou 100%.
