### ISSUE TITLE
To separate with points

### ISSUE THREAD

**Issue by newmesiss** [assisrafael/angular-input-masks#271]
I would like to know how I can separate the numbers with dots and not with commas
Attached image as it appears to me

<input class="l-input" ng-model="vm.afp" ui-number-mask="0" />

![be1df4338609410bb75f6f26855038e7 1](https://cloud.githubusercontent.com/assets/5264883/25533658/b856a732-2c07-11e7-8628-80e5daa4128f.png)

**Comment by newmesiss** [comment]
Solve it, only adding https://docs.angularjs.org/guide/i18n

**Comment by assisrafael** [comment]
This is also described in the README: https://github.com/assisrafael/angular-input-masks#internationalization
