### ISSUE TITLE
TypeError ao carregar a página

### ISSUE THREAD

**Issue by thandrade88** [assisrafael/angular-input-masks#279]
Quando carrego a página no meu console aparece o seguinte erro:

angular.js:9563 TypeError: Cannot set property 'cpf' of undefined

E indica que o erro é nessa função:

angular.forEach(maskDefinition.validations, function(validatorFn, validationErrorKey) {
	ctrl.$validators[validationErrorKey] = function validator(modelValue, viewValue) { //nessa linha o erro
		return ctrl.$isEmpty(modelValue) || validatorFn(modelValue, viewValue);
	};
});

Como resolver?

**Comment by milrak** [comment]
Conseguiu resolver o problema? (Estou passando pelo mesmo caminho, sabe me dizer qual o atalho?)

**Comment by assisrafael** [comment]
Can you post a small piece of code that behaves as you described?

**Comment by milrak** [comment]
Solved problem:
https://pt.stackoverflow.com/questions/94942/como-usar-angular-input-mask/94974?noredirect=1#comment488754_94974

Thank you so much for the attention rafael, great solution.

**Comment by thandrade88** [comment]
Thank you
