### ISSUE TITLE
Problema ao exibir as mascaras no celular

### ISSUE THREAD

**Issue by luizrita** [assisrafael/angular-input-masks#280]
Ola, meu nome é Luiz.

Ao tentar acessar as pagina de demonstração, e digitar qualquer valor a exibição da mascara não funciona como em um PC.
Ex.: Para mascaras como CPF ou CNPJ é necessário colocar o ponto ou o cursor se perde e fica antes do ultimo numero digitado.
Para valores numéricos o cursor se perde entre os separadores, além do cursor nunca permanecer alinhado a direita como é no PC.

**Comment by cafe01** [comment]
Alguma luz? Estou com o mesmo problema... 
Encontrei esse modulo para substituir outro module de mask que por conta desse mesmo problema:
https://github.com/angular-ui/ui-mask/pull/26

**Comment by luizrita** [comment]
Achei esse código mas to tendo problema com inputs do tipo checkbox e radio.
`$element.bind('keydown', function($event) {
					if($event.keyCode != 8) {
						$timeout(function() {
							$event.target.selectionStart = $event.target.value.length;
							$event.target.selectionEnd = $event.target.value.length;
						});
					}
				});`

**Comment by assisrafael** [comment]
Duplicate of #104
