### ISSUE TITLE
Dificuldade em instalar no Ionic 3

### ISSUE THREAD

**Issue by eduardobrunetti** [assisrafael/angular-input-masks#284]
Ola amigos, estou com dificuldade em instalar no meu projeto em Ionic 3. Infelizmente sou novo em ionic e angular e não estou sabendo como declarar no modulo. Se poderem ajudar eu agradeço. Abraços.

**Comment by assisrafael** [comment]
Esta biblioteca não é compatível com ionic 3 ainda.
