### ISSUE TITLE
Methods Save

### ISSUE THREAD

**Issue by lclpedro** [assisrafael/angular-input-masks#288]
Hello, is possible save point? CPF, CPNJ, Dates?

**Comment by assisrafael** [comment]
I'm not sure what is your question about. Can you explain it with an example?

**Comment by lclpedro** [comment]
Is saved in database 0123467890! Is possible save 012.345.678-90? Save points..

**Comment by assisrafael** [comment]
Not without extra code.
Take a look at https://github.com/assisrafael/angular-input-masks#filters
Duplicate of #172
