### ISSUE TITLE
npm install --prod not working

### ISSUE THREAD

**Issue by MarcosSpessatto** [assisrafael/angular-input-masks#303]
It's not possible to install dependencies only for production, as there is a postinstall in package.json that runs the webdriver-manager update, because the webdriver is installed only as devDependencies, so when run npm run webdriver, the build breaks does not find the webdriver, since the installation is only of the dependencies and not of the devDependencies

**Comment by wcustodio** [comment]
Same problem here. It's not possible to install by `npm install --save angular-input-masks`.

**Comment by marcoskubis** [comment]
Install angular webdriver manager by runnning:

`npm install -g webdriver-manager`

Then install the package:

`npm install --save angular-input-masks`

**Comment by assisrafael** [comment]
There is an open pull request for this issue that needs some work before being accepted.
