### ISSUE TITLE
Can we have a release with the additional data mask locales?

### ISSUE THREAD

**Issue by dsaita** [assisrafael/angular-input-masks#337]
Five months ago new locales were added to https://github.com/assisrafael/angular-input-masks/blob/master/src/global/date/date.js but there is no release of angular-input-masks-standalone with those locales.

**Comment by assisrafael** [comment]
Done, check version 4.2.

**Comment by dsaita** [comment]
FYI, The new version ui-date-mask uses `var parseDate = require('date-fns/parse');` and for some reason, parsing '18/05/2018' with format 'DD/MM/YYYY' returns `Wed Jan 18 2017 00:00:00 GMT-0200 (-02)`
