### ISSUE TITLE
Keep the mask in the model

### ISSUE THREAD

**Issue by moisespio** [assisrafael/angular-input-masks#34]
Hello folks!

Is there any way to keep the mask (with the symbols) in the model?

Thanks!

**Comment by wellermiranda** [comment]
Hi, 

I want to keep the mask too.

Thanks!

**Comment by assisrafael** [comment]
Not yet.
Can you describe a few examples of this use case?

**Comment by moisespio** [comment]
I'm using the phone mask in a form and I want to send a email on submit. That's why I want to keep the mask, because I want to receive a email with the formatted phone number.

**Comment by assisrafael** [comment]
We do not have plans to implement this behavior.

An alternative for your scenario is to use the [angular-br-filters](https://github.com/the-darc/angular-br-filters) to apply the mask again in the model value.

**Comment by moisespio** [comment]
Thanks, this is a good alternative ;)

**Comment by wellermiranda** [comment]
@assisrafael I need to keep the mask to send it to an api, when it will be saved. Do you have an alternative? Thanks :)

**Comment by assisrafael** [comment]
Maybe you can write a transformRequest property on the configuration object passed into $http. See https://docs.angularjs.org/api/ng/service/$http for more details

**Comment by assisrafael** [comment]
Feel free to reopen this issue if necessary.

**Comment by pocesar** [comment]
@wellermiranda @moisespio http://ngmodules.org/modules/angular-cleanmask

**Comment by awerlang** [comment]
@moisespio @wellermiranda @pocesar I needed an input mask that can handle model values with mask, by default, and made the following solution https://github.com/awerlang/angular-easy-masks, hope it helps
