### ISSUE TITLE
ui.utils.masks.ie

### ISSUE THREAD

**Issue by nandofalcao** [assisrafael/angular-input-masks#39]
Ao selecionar alguns estados na diretiva de Inscrição Estadual, dá um erro:
### "Cannot read property 'length' of undefined"

O estados são:
### BA,PE e RN

Grato!

**Comment by assisrafael** [comment]
The protractor tests are working fine with these states.
Can you provide more details (browser, angular version, model value and type, etc)?

**Comment by nandofalcao** [comment]
O erro estava em uma adaptação que realizei na diretiva "IE", onde faço com que a validação seja feita no momento em que uma nova "UF" é selecionado no dropdown.

Agora está ok!

Obrigado!
