### ISSUE TITLE
bower-angular-input-masks

### ISSUE THREAD

**Issue by assisrafael** [assisrafael/angular-input-masks#46]
move release files to a separate repository.

Tasks:
- [x] create and configure repository
- [x] copy every release and tags to the new repository
- [x] change bower registry
- [x] remove release folder from this repository
- [x] bower-release script

**Comment by assisrafael** [comment]
Releases copied: 1.0.10, 1.1.3, 1.2.5, 1.3.0, 1.3.1

**Comment by Russian60** [comment]
do it again please :/
