### ISSUE TITLE
Percentage mask do not apply when value is 0

### ISSUE THREAD

**Issue by faelcorreia** [assisrafael/angular-input-masks#52]
Hi Rafael.

There is an issue when the model of the input is 0. It seems like the ui.utils.masks.global.percentage ignores it.

Here is a Plunker with the problem. I'm using the 1.4.0.

http://plnkr.co/edit/Eh8s375HCgnsuM7WXwDv?p=preview

I tried to understand the conversion but my knowledge on Angular is too limited yet.

Thanks!

**Comment by faelcorreia** [comment]
I checked your commit c14eca6a9a562a915ce599452433b8e31e29be57 and you resolved the same problem for money. 

Now I'm using "if(angular.isUndefined(value))" instead of "if(!value)" and problem is solved.

Pull request sent.

**Comment by assisrafael** [comment]
Fixed in version 1.4.1
