### ISSUE TITLE
Keep mask but allow optional fields

### ISSUE THREAD

**Issue by pocesar** [assisrafael/angular-input-masks#62]
I want to keep the mask of an optional field, but still want the mask on it. Setting ng-model-options to allowInvalid have no effect. Should either check for `required` attribute, or check ng-model-options using `require: ['?ngModel', '?ngModelOptions']`

**Comment by assisrafael** [comment]
This lib was built using angular 1.2.X features and ngModelOptions is a 1.3.X feature.
Feel free to make a PR updating this lib to the 1.3.x features, however keep in mind that this might cause breaking changes and drop 1.2 support.

**Comment by assisrafael** [comment]
This should be fixed in version 2.0. Please open a new ticket if this is still an issue!
