### ISSUE TITLE
Desabilitar validação CPF

### ISSUE THREAD

**Issue by talski** [assisrafael/angular-input-masks#65]
Tem alguma possibilidade de desabilitar a validação do CPF?

Gostaria de deixar somente a mascara pois faço a validação no servidor, do modo atual ele lança um erro falando que o cpf é inválido antes de enviar as informações pro servidor.

**Comment by assisrafael** [comment]
At the moment no.

**Comment by awerlang** [comment]
@talski veja aqui https://github.com/awerlang/angular-easy-masks
