### ISSUE TITLE
Error when loading data from API

### ISSUE THREAD

**Issue by isaquedias** [assisrafael/angular-input-masks#67]
I'm using the ui-money-mask, and I have a problem when I receive the number from API. It's probably occurring because the mask is rendering before the data is loaded. It throws "undefined is not a function" error on mask.js:1293. 
```javascript
return moneyMask.apply(value.toFixed(decimals).replace(/[^\d]+/g,''));
```

My code: 
```javascript
<input type="text" class="form-control" ng-model="tabela.preco" ui-money-mask required>
```

Thank you.

**Comment by assisrafael** [comment]
Which version of angular-input-masks you are using?

**Comment by isaquedias** [comment]
Version 1.2.3

**Comment by assisrafael** [comment]
Upgrade to 1.4.1 and check if the error persist.

**Comment by isaquedias** [comment]
Solved! Thank you.
