### ISSUE TITLE
IE8 reserved word

### ISSUE THREAD

**Issue by kermtfrg** [assisrafael/angular-input-masks#71]
I tried to use your library in IE8 and it immediately blew up.  In the definition of var tokens the use of "default" is causing problems because it is a reserved word.  If I changed it to _default the library works perfectly in IE8.

**Comment by assisrafael** [comment]
Unfortunately, I do not have plans to support IE8.
However, feel free to submit a PR if you want.
Keep in mind that angular 1.3 has removed [IE8 support](https://github.com/angular/angular.js/commit/eaa1d00b24008f590b95ad099241b4003688cdda).
