### ISSUE TITLE
remove $log.debug disable

### ISSUE THREAD

**Issue by simpixelated** [assisrafael/angular-input-masks#72]
Why disable $log.debug here: https://github.com/assisrafael/angular-input-masks/blob/2ea7504b30056e34e872ac872d564e847e83cadd/src/masks.js#L18

When included as a dependency, this disabled $log.debug in my app. I had to override the line in my own app to get back to the default state (enabled).

**Comment by assisrafael** [comment]
Landed in v1.5.1.
