### ISSUE TITLE
Error on phonenumber as Number field

### ISSUE THREAD

**Issue by begrossi** [assisrafael/angular-input-masks#73]
Hi, I'm using phonenumber field as Number. I had a problem with ui-br-phone-number, that crashes on removeNonDigits function. I changed it to the above code to fix:

	function removeNonDigits(value) {
        if (value && typeof value=="string")
		    return value.replace(/[^0-9]/g, '');
        return value;
	}

**Comment by assisrafael** [comment]
Please, check if 340ee6d742db1c70ad96da1c6aa0b35dc94f38ea fixed your issue.

**Comment by assisrafael** [comment]
Landed in v1.5.1.
