### ISSUE TITLE
Máscara de boleto bancário

### ISSUE THREAD

**Issue by bernardolm** [assisrafael/angular-input-masks#74]
Já que possui máscaras para o Brasil, uma de boleto bancário seria ótimo! ;)

**Comment by assisrafael** [comment]
Can you describe the pattern?

**Comment by bernardolm** [comment]
O padrão é 99999.99999 99999.999999 99999.999999 9 99999999999999 onde:

Posição 01-03 = Identificação do banco (exemplo: 001 = Banco do Brasil)
Posição 04-04 = Código de moeda (exemplo: 9 = Real)
Posição 05-09 = 5 primeiras posições do campo livre (posições 20 a 24 do código de barras)
Posição 10-10 = Dígito verificador do primeiro campo
Posição 11-20 = 6ª a 15ª posições do campo livre (posições 25 a 34 do código de barras)
Posição 21-21 = Dígito verificador do segundo campo
Posição 22-31 = 16ª a 25ª posições do campo livre (posições 35 a 44 do código de barras)
Posição 32-32 = Dígito verificador do terceiro campo
Posição 33-33 = Dígito verificador geral (posição 5 do código de barras)
Posição 34-37 = Fator de vencimento (posições 6 a 9 do código de barras)
Posição 38-47 = Valor nominal do título (posições 10 a 19 do código de barras)

**Comment by bernardolm** [comment]
Um exemplo de um boleto válido: 

10491.44338 55119.000002 00000.000141 3 25230000093423

**Comment by awerlang** [comment]
@bernardolm veja se te atende: https://github.com/awerlang/angular-easy-masks

**Comment by assisrafael** [comment]
Landed in v1.5.1.
However, the validation is only checking the length.

**Comment by bernardolm** [comment]
@assisrafael ;]
