### ISSUE TITLE
Compatibility with Angular 1.3.x

### ISSUE THREAD

**Issue by frekele** [assisrafael/angular-input-masks#77]
I changed the angular of version 1.2.28 to 1.3.15 and is working 'perfectly.'
I recommend the change in bower.json

FROM
>"dependencies": {
>   "angular": "~1.2.26"
> },

TO
>"dependencies": {
>   "angular": ">=1.2.9 <1.4.0",
> },

**Comment by assisrafael** [comment]
All tests have passed?

**Comment by assisrafael** [comment]
Using angular 1.3.15 a lot of protractor tests broke:
```
Finished in 130.14 seconds
69 tests, 1961 assertions, 139 failures
```

**Comment by assisrafael** [comment]
The migration to angular 1.3.X will need some refactorings.

**Comment by frekele** [comment]
Sorry, I not run the tests. only i tried in my app.
But in my apps is working perfectly with angular 1.3.15.

**Comment by frekele** [comment]
I will make a fork and do everything possible to contribute to the compatibility for angular 1.3.x, in this project; :)

Once i have time, i will get the source code to help you.

**Comment by assisrafael** [comment]
Nice.
Make a PR when your code is ready.

**Comment by ivanhtp** [comment]
+1

**Comment by pdf13** [comment]
+1

**Comment by LucasSubli** [comment]
+1
While at it make it 1.4.1 compatible too
