### ISSUE TITLE
Uncaught TypeError: object is not a function

### ISSUE THREAD

**Issue by rafaelzomer** [assisrafael/angular-input-masks#88]
When i try to include the lib in my project like described in the README.md

`1. Import the releases/angular-input-masks-standalone.min.js script in your page.`
`2. Include the module ui.utils.masks in your angular app.`
`3. Include the ui-mask directive in a text field like the examples abouve`

I recieve the following error: (Google Chrome)
`Uncaught TypeError: object is not a function`
at this line
`var cnpjPattern = new StringMask('00.000.000\/0000-00');`

I tried another ways, like including 'angular-input-masks' and 'angular-input-masks-dependencies' but nothing worked. I recieve the same error everytime. I am using require.js to include the files.

**Comment by assisrafael** [comment]
You have tried to use the lib without require.js?
Include it directly into the html e check if the error persist, please.

**Comment by rafaelzomer** [comment]
It worked. I think that i discover the problem, the "require" in your lib conflicts with the "require" from requirejs. When I include "angular-input-masks" before "require.js" i recieve the following error: `Uncaught TypeError: require.config is not a function`. The require in your code is a 3rd lib or something like? Because i can try rename it with grunt.

**Comment by assisrafael** [comment]
It's browserify's require. Check if there is some procedure to achieve interoperability between them.

**Comment by assisrafael** [comment]
Check if this solves your issues: http://stackoverflow.com/questions/24168851/using-browserify-and-requirejs-on-the-same-page
Feel free to reopen this issue.
