### ISSUE TITLE
Salvar Mascaras no Banco de Dados

### ISSUE THREAD

**Issue by edgardksb** [assisrafael/angular-input-masks#89]
Olá.

Muito bom seu projeto. Parabens !!.

Tem alguma opção que consigo habilitar para quando pegar os dados no ngModel, as mascaras continuem ???

No seu demo http://assisrafael.github.io/angular-input-masks/ o model value vem sempre sem mascara.

**Comment by assisrafael** [comment]
At the moment no.
But you could write a directive that assigns the $viewValue to another model, or, you could use https://github.com/the-darc/br-masks to apply the mask again before submitting the values to server.
