### ISSUE TITLE
Error: Cannot find module 'string-mask'

### ISSUE THREAD

**Issue by Falci** [assisrafael/angular-input-masks#92]
After install, I see the following error:

```Uncaught Error: Cannot find module 'string-mask'```
```Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module ui.utils.masks due to:
Error: [$injector:nomod] Module 'ui.utils.masks' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.```

_bower.json_
```
{
  "dependencies": {
    "angular": "~1.4.1",
    "angular-ui-router": "~0.2.15",
    "bootstrap": "~3.3.5",
    "angular-bootstrap": "~0.13.0",
    "font-awesome": "~4.3.0",
    "bootstrap-tagsinput": "~0.5.0",
    "bootstrap-treeview": "~1.2.0",
    "jquery-loader": "*",
    "angular-breadcrumb": "~0.4.0",
    "angular-resource": "~1.4.1",
    "angular-local-storage": "~0.2.2",
    "angular-input-masks": "~1.5.1",
    "angular-br-filters": "~0.4.0"
  },
  "resolutions": {
    "angular": "~1.4.1",
    "string-mask": "^0.2.1"
  }
}
```

Is it an error with dependencies resolution ?

**Comment by diego-vieira** [comment]
Same here.
I notice the following tho
```javascript
require('./global/global-masks'),
require('./br/br-masks'),
require('./us/us-masks')
```
but those files doesn't exist when installing using bower?

**Comment by diego-vieira** [comment]
All good here, add the reference to angular-input-masks-standalone.js

**Comment by assisrafael** [comment]
It seems that the build script has a bug.

**Comment by diego-vieira** [comment]
@assisrafael using the standalone file worked just fine here FYI.

**Comment by assisrafael** [comment]
You are using through bower or npm?

**Comment by diego-vieira** [comment]
bower

**Comment by Falci** [comment]
Following the @diego-vieira's comments, I fixed with:
```
  "overrides": {
    "angular-input-masks": {
      "main": [
        "angular-input-masks-standalone.js"
      ]
    }
}
```

**Comment by assisrafael** [comment]
Fixed in version 1.5.2.

**Comment by diegopso** [comment]
I was using the version 2.0 and got the same error. I've fixed going back to 1.5.2.

**Comment by fauker** [comment]
![captura de tela 2016-02-05 as 14 27 14](https://cloud.githubusercontent.com/assets/7989766/12852128/9f364978-cc14-11e5-9bd0-7825a475e0cb.png)

I tried the latest version and the 1.5.2 version, as @diegopso said.

I'm trying with RequireJS: 

Importing `angular-input-masks-standalone.min` and injecting`'ui.utils.masks'` in my module.

Help.

**Comment by peder** [comment]
Does `string-mask` not export correctly?

![image](https://cloud.githubusercontent.com/assets/1018574/22841803/8df75a14-ef98-11e6-998b-e113c1169673.png)

I don't want to include an enormous file in my project that also references moment.js, since my project already pulls in moment.js. I'm curious if anyone else has come across this.

**Comment by tiagoemerick** [comment]
My case resolved when i put an order to export the scripts that was:

angular-input-masks-standalone.min.js,
angular-input-masks-dependencies.min.js,
angular-input-masks.min.js,
angular-input-masks.br.min.js
