### ISSUE TITLE
ui-number-mask - issue -  undefined when used another directive

### ISSUE THREAD

**Issue by mskichu** [assisrafael/angular-input-masks#94]
Firstly thank you for the directive. I started using this directive and found an issue when used with input spinner. I'm trying to create a directive  just like https://jqueryui.com/spinner/. using bootstrap. Basically every thing work as desired except when the down arrow reaches value "0" the the control renders to undefined. I suspect when decimals = 0 are directive it set value  ui-number-mask='0'. I understand the directive is not complete functionally. But it works to show the error. I may not be using the ui-mask-number correctly help is needed please. Thanks in advance

Sorry I have not mentioned that I'm using v2.0.0

(function () {
    "use strict";

```
var app = angular.module("appdirective");
app.directive("prnumberspinner", directivectrl);
```

////////////////////////////////////////////////////////////////
// define
    directivectrl.$inject = ['$timeout','$compile'];
    function directivectrl($timeout,$compile) {

```
    ///<summary>
//    /// Usage:
                //<div prnumberspinner isrequired="false" incrementvalue="0.01" decimals="2"
                //    item-value="svt.servicetypemodel.BudgetedHours" ng-model="svt.servicetypemodel"
                //    max="1000" min="0" fieldname="[[[Targeted Hours]]]"
                //    inputsize="small"></div>
    ///
    ///</summary>
    ///<returns></returns>


    var directive = {
        restrict: 'A',
        require: 'ngModel',
        replace: 'true',
        symbol: '=?',
        scope: {

            isrequired: '=',
            incrementvalue:"=",
            decimals: '@',
            itemValue: "=",
            max:"@",
            min:"@",
            fieldname:'@',
            inputsize: "@"

        },
        template: '<div>' +
                    '<div class="input-group spinner-sm">'+
                    '<input type="text" class="form-control" ' +
                    ' ng-model = "itemValue"'+
                    ' ui-number-mask = "{{decimals}}"'+
                    ' ui-negative-number'+
                    ' ui-hide-group-sep '+
                    ' ng-required="isrequired" ' +
                    ' min="{{min}}"'+
                    ' max="{{max}}"' +
                    ' id={{inputid}}'+
                    ' ng-attr-name="{{fieldname}}">'+
                        '<div class="input-group-btn-vertical">'+
                            '<button class="btn btn-default" type="button" ng-disabled="updisable" ng-click="upClicked($event)"><i class="fa fa-caret-up"></i></button>'+
                            '<button class="btn btn-default" type="button" ng-disabled="downdisable" ng-click="downClicked($event)"><i class="fa fa-caret-down"></i></button>'+
                        '</div> </div>'+
                     '<div ng-show="notvalid" class="has-error">[[[Please enter a valid number between {{minvalue}} and {{maxvalue}} ]]] </div>' +
                '</div>',
        link: linker
    };

    return directive;
    function linker(scope, element, attrs, modelCtrl) {

         scope.inputid=scope.$id+"input";
         scope.notvalid=false;
         scope.updisable=false;
         scope.downdisable=false;

        if(!scope.itemValue)
        {
            scope.itemValue=0;
        }
        var inputelement=[];
        if (scope.inputsize == "medium") {
          inputelement = element.find(".spinner-sm");
            inputelement.removeAttr("class");
            inputelement.attr('class', 'input-group spinner-md');
        }
        else if (scope.inputsize == "large") {
             inputelement = element.find(".spinner-sm");
            inputelement.removeAttr("class");
            inputelement.attr('class', 'input-group spinner-lg');
        }
        else
        {
             inputelement = element.find(".spinner-sm");
            inputelement.removeAttr("class");
            inputelement.attr('class', 'input-group spinner-sm');
        }

        if(scope.decimals<=0)
        {
           // inputelement = element.find("#"+scope.inputid);
            //inputelement.removeAttr("ui-number-mask");
            //inputelement.attr("ui-number-mask");
            //$compile(element.contents())(scope);
        }





        scope.upClicked=function($event)
        {
            // get the input value
            var inputValue = parseInt(scope.itemValue);
            var totalvalue = 0;
            if(angular.isNumber(inputValue))
            {
                // Now check the dev as specified float
                if(angular.isNumber(scope.decimals) && scope.decimals>0)
                {
                    // parse the input as decimal
                    inputValue = parseFloat(scope.itemValue);
                    totalvalue = parseFloat(scope.incrementvalue)+ inputValue;
                }
                else
                {
                    // parse the input as decimal
                    inputValue = parseInt(scope.itemValue);
                    totalvalue = parseInt(scope.incrementvalue)+ inputValue;
                }

                if(totalvalue<=scope.max)
                {
                   scope.itemValue = totalvalue;
                    scope.downdisable=false;
                }
                else{
                    scope.updisable=true
                }
            }

            $event.stopPropagation();
        };


        scope.downClicked=function($event)
        {
            // get the input value
            var inputValue = parseInt(scope.itemValue);
            var totalvalue = 0;
            if(angular.isNumber(inputValue))
            {
                // Now check the dev as specified float
                if(angular.isNumber(scope.decimals) && scope.decimals>0)
                {
                    // parse the input as decimal
                    inputValue = parseFloat(scope.itemValue);
                    totalvalue = inputValue - parseFloat(scope.incrementvalue);
                }
                else
                {
                    // parse the input as decimal
                    inputValue = parseInt(scope.itemValue);
                    totalvalue = inputValue - parseInt(scope.incrementvalue);
                }

                scope.itemValue = totalvalue;

                // This need revisiting.
                //if(totalvalue >= scope.min)
                //{
                //
                //
                //}
                //else{
                //    scope.itemValue = 0;
                //    scope.downdisable=true;
                //}
            }
            $event.stopPropagation();

        };

        // set the form dirty means something has been changed
        var formdirty = function () {
            if (scope.notformfield) {
                modelCtrl.$setDirty = angular.noop
            }
            else {
                modelCtrl.$setDirty();
            }

        };


        scope.$watch('itemValue',function(newvalue){
            // get the input value

        });






    }


}
```

})();'''
##

**Comment by assisrafael** [comment]
Can you provide a live demo?

**Comment by mskichu** [comment]
Please find the plunk requested

http://embed.plnkr.co/jhBCDLOvi9RGaitY2w9y/preview

**Comment by assisrafael** [comment]
Do you tried to put a breaking point (debug) the parser method of NumberMaskDirective?
In your plunker this function is only called once, when the directive is compiled.
So the undefined value is the result of your directive.

Let me know if I am wrong.

**Comment by mskichu** [comment]
yes I did debug before posting  sorry I disagree, if I comment use of ui-number-mask in the directive my code works fine but if I enable the ui-number-mask it does not, so I may be using the ui number mask incorrectly or there could be issue on this.

**Comment by assisrafael** [comment]
Looking again, if you put a breaking point in the formatter method of NumberMaskDirective, you can see that this method is called every time the model is updated. Maybe the formatter method is the source of the undefined value.

However, take a look at this plunker: http://embed.plnkr.co/xOXwmpHXEDBcIo2SlEet/preview
Setting the value to 0 is not the problem.

**Comment by nschlatter** [comment]
I am having a similar issue.  i installed using bower a couple of hours ago.  I am setting ui-number-mask="0" and if the value i am binding to in ng-model is 0, it says undefined in the text box.

**Comment by assisrafael** [comment]
@nschlatter you are using which angular version?

**Comment by nschlatter** [comment]
I am using version 1.3.14

Actually, when I bind to a field that is 0, it works as described.  In my case, I am binding to a field on an object that is 0 (i.e. ngModel="vm.product.quantity").

**Comment by nschlatter** [comment]
It looks like this was happening for me if i did not initialize the object's member field that I was binding to before populating the field with a zero in a service callback method.  Once I initialized the object's field that I was binding to (BEFORE: vm.product = {};  AFTER: vm.product = { quantity: 0 };) it showed zero like expected.  I hope that that helps!

**Comment by mskichu** [comment]
I have tested and found that undefined is fired on the code below  
'''prefix + viewMask.apply(valueToFormat);
           
''' var prefix = (angular.isDefined(attrs.uiNegativeNumber) && value < 0) ? '-' : '';
			var valueToFormat = PreFormatters.prepareNumberToFormatter(value, decimals);
			//   var somevalue = prefix + viewMask.apply(valueToFormat);
			  // console.log(somevalue);
				return prefix + viewMask.apply(valueToFormat);
			}'

**Comment by mskichu** [comment]
I have changed the code on uiNumberMask directive to suite my need but I would like someone to have code review please find the plunk  http://embed.plnkr.co/jhBCDLOvi9RGaitY2w9y/preview 
The changes are made to angular-input-mask directive. Please note these changes are waiting for owners approval.

**Comment by assisrafael** [comment]
Make a pull request, it will be easier to review your code.

**Comment by mskichu** [comment]
I have made the pull request. Do I have a push permissions it seems not as I get permissions issue.

**Comment by assisrafael** [comment]
Are you sure? Your pull request is not listed yet: https://github.com/assisrafael/angular-input-masks/pulls

Take a look at: https://help.github.com/articles/using-pull-requests/

**Comment by mskichu** [comment]
sorry its my mistake for some reasons I cloned it ( ya terribly of me) I have committed to develop...

**Comment by BenMGilman** [comment]
+1 is this fix going to be released anytime soon?

**Comment by almothafar** [comment]
+1 any fix for this, i'm getting same issue, without ui-money-mask it is working, with it, undefined !

simply its `<input ui-money-mask="0" ui-hide-space ng-model="data.amount" placeholder="Enter an Amount" size="10" required type="tel" pattern="[0-9]*" maxlength="5" min="1">`

 as a modal template.

**Comment by mskichu** [comment]
Hello,
No I'm not using this library any more but this has helped me create my own
specific my project.
Kind Regards

Kichu

**Comment by assisrafael** [comment]
Possibly fixed in latest version.
