### ISSUE TITLE
RequireJS

### ISSUE THREAD

**Issue by tiagoadp** [assisrafael/angular-input-masks#99]
Olá, estou usando require.js com schim... A nova versão que vc criou a 2.0 não roda nem por reza...

A antiga da demo fica 100% porem está desatualizada... Queria ver com vc se tem como vc fazer um pacote sem usar bower e o método de módulos com pastas, etc... No estilo que vc fez a antiga...

Porque hoje eu uso o require.js com angular.js on demand... e tudo funciona, eu tive que usar o moment antigo da 2.3, porque o novo não funciona com escopo global e ai muitos plugins não funcionam sem o moment tmb.. enfim é complicado... :(

Aguardo retorno. Abração.

**Comment by assisrafael** [comment]
Have you tried the angular-input-masks-standalone.js surrounded by a IIFE?

**Comment by tiagoadp** [comment]
Yes, but i got the same error:

Uncaught TypeError: object is not a function

My require.config is like this:

require.config({
    paths: {
	'angular-input-masks': './content/libs/angular/angular-input-masks-new',
	'br-validations': './content/libs/br-validations.min',
	'string-mask': './content/libs/string-mask',
	'moment': './content/libs/moment-with-locales',
    },
    shim: {
	'angular-input-masks': {
            deps: ['angular', 'string-mask', 'br-validations', 'moment']
        },
	'app': {
		    deps: ['angular', 'angular-input-masks']
		},
    }
});

require
(
    [
        'app'
    ],
    function(app)
    {
        angular.bootstrap(document, ['app']);
    }
);

**Comment by tiagoadp** [comment]
Any other idea to make it work?

**Comment by tiagoadp** [comment]
The solution was so dumb... remove the require= from the beginning of the object T_T

**Comment by assisrafael** [comment]
Closing since you found a workaround.

**Comment by aj07mm** [comment]
@tiagoadp what you mean `require=`? Can you paste a sample?
I am having the same trouble

**Comment by aj07mm** [comment]
this works:

`require.config({
	paths: {
		'angular': 'js/libs/angular/angular.min',
		'moment': 'js/libs/moment/moment.min',
		'string-mask': 'js/libs/string-mask/string-mask',
		'br-validations': 'js/libs/br-validations/br-validations',
		'angular-input-masks': 'js/libs/angular-input-masks/angular-input-masks',
	},
	shim: {
		'angular-input-masks': ['angular', 'string-mask', 'moment', 'br-validations'],
		'angular': {exports: 'angular'}
	},
	baseUrl: '/static'
});

require(['modules/app'], function(app) {
	app.init();
});
`
